github.com:
    users:
        yoonseocho:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: yoonseocho
